# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import auth_pb2 as proto_dot_auth__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in proto/auth_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.authentication = channel.unary_unary(
            "/grpc.AuthService/authentication",
            request_serializer=proto_dot_auth__pb2.AuthRequest.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.AuthResponse.FromString,
            _registered_method=True,
        )
        self.registrate = channel.unary_unary(
            "/grpc.AuthService/registrate",
            request_serializer=proto_dot_auth__pb2.AuthRequest.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.AuthResponse.FromString,
            _registered_method=True,
        )
        self.logout = channel.unary_unary(
            "/grpc.AuthService/logout",
            request_serializer=proto_dot_auth__pb2.Token.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.SuccessResponse.FromString,
            _registered_method=True,
        )
        self.refresh_token = channel.unary_unary(
            "/grpc.AuthService/refresh_token",
            request_serializer=proto_dot_auth__pb2.Token.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.AuthResponse.FromString,
            _registered_method=True,
        )
        self.get_user = channel.unary_unary(
            "/grpc.AuthService/get_user",
            request_serializer=proto_dot_auth__pb2.Token.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.User.FromString,
            _registered_method=True,
        )
        self.verify = channel.unary_unary(
            "/grpc.AuthService/verify",
            request_serializer=proto_dot_auth__pb2.Token.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.SuccessResponse.FromString,
            _registered_method=True,
        )
        self.change_password = channel.unary_unary(
            "/grpc.AuthService/change_password",
            request_serializer=proto_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
            response_deserializer=proto_dot_auth__pb2.SuccessResponse.FromString,
            _registered_method=True,
        )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def authentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def registrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def refresh_token(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def get_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def change_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "authentication": grpc.unary_unary_rpc_method_handler(
            servicer.authentication,
            request_deserializer=proto_dot_auth__pb2.AuthRequest.FromString,
            response_serializer=proto_dot_auth__pb2.AuthResponse.SerializeToString,
        ),
        "registrate": grpc.unary_unary_rpc_method_handler(
            servicer.registrate,
            request_deserializer=proto_dot_auth__pb2.AuthRequest.FromString,
            response_serializer=proto_dot_auth__pb2.AuthResponse.SerializeToString,
        ),
        "logout": grpc.unary_unary_rpc_method_handler(
            servicer.logout,
            request_deserializer=proto_dot_auth__pb2.Token.FromString,
            response_serializer=proto_dot_auth__pb2.SuccessResponse.SerializeToString,
        ),
        "refresh_token": grpc.unary_unary_rpc_method_handler(
            servicer.refresh_token,
            request_deserializer=proto_dot_auth__pb2.Token.FromString,
            response_serializer=proto_dot_auth__pb2.AuthResponse.SerializeToString,
        ),
        "get_user": grpc.unary_unary_rpc_method_handler(
            servicer.get_user,
            request_deserializer=proto_dot_auth__pb2.Token.FromString,
            response_serializer=proto_dot_auth__pb2.User.SerializeToString,
        ),
        "verify": grpc.unary_unary_rpc_method_handler(
            servicer.verify,
            request_deserializer=proto_dot_auth__pb2.Token.FromString,
            response_serializer=proto_dot_auth__pb2.SuccessResponse.SerializeToString,
        ),
        "change_password": grpc.unary_unary_rpc_method_handler(
            servicer.change_password,
            request_deserializer=proto_dot_auth__pb2.ChangePasswordRequest.FromString,
            response_serializer=proto_dot_auth__pb2.SuccessResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "grpc.AuthService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("grpc.AuthService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def authentication(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/authentication",
            proto_dot_auth__pb2.AuthRequest.SerializeToString,
            proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def registrate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/registrate",
            proto_dot_auth__pb2.AuthRequest.SerializeToString,
            proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def logout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/logout",
            proto_dot_auth__pb2.Token.SerializeToString,
            proto_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def refresh_token(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/refresh_token",
            proto_dot_auth__pb2.Token.SerializeToString,
            proto_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def get_user(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/get_user",
            proto_dot_auth__pb2.Token.SerializeToString,
            proto_dot_auth__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def verify(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/verify",
            proto_dot_auth__pb2.Token.SerializeToString,
            proto_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def change_password(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc.AuthService/change_password",
            proto_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
            proto_dot_auth__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
